version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-restaurant
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: walid123
      MYSQL_DATABASE: RestaurantDB
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-network

volumes:
  mysql_data:

networks:
  spring-network:
    driver: bridge
