spring.application.name=mcp-client

spring.ai.openai.api-key=
spring.ai.openai.base-url=https://api.openai.com
spring.ai.openai.chat.options.model=gpt-4.1
spring.ai.openai.chat.options.temperature=1
spring.ai.openai.chat.options.max-completion-tokens=1024


spring.ai.mcp.client.sse.connections.server1.url=http://restaurant-app:9090
spring.ai.mcp.client.sse.connections.server1.sse-endpoint=/sse
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.type=SYNC

#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/auth
#spring.security.oauth2.ressourceserver..jwt.decoder-secret =